FROM mrlyc/ubuntu-ssh:latest

MAINTAINER lyc <imyikong@gmail.com>

EXPOSE 22
EXPOSE 8080

ADD build.sh /build.sh
ADD entry.sh /entry.sh

ENV DOCKER_DEBUG 0
ENV AUTHORIZED_KEYS ""
ENV ROOT_PASS ""
ENV INITSH ""

ENV MINICRONSH ""
ENV PORT 8080
ENV SERVER_API_HOST "0.0.0.0"
ENV SERVER_SESSION_SECRET imyikong
ENV DB_TYPE sqlite
ENV DB_HOST ""
ENV DB_NAME ""
ENV DB_USER ""
ENV DB_PASSWORD ""

EXPOSE 8080

WORKDIR /
RUN ["/build.sh"]

ENTRYPOINT ["/entry.sh"]
